source 'https://rubygems.org'

gem 'rails', '4.2.5.1'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'slim-rails'
gem 'coffee-rails', '~> 4.1.0'
gem "delayed_job"
gem "delayed_job_active_record"

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'spring'
end

