# A sample Gemfile
source "https://rubygems.org"


# gem "activerecord", '4.1.7'
# gem 'mysql2', '~> 0.3.17'
gem "activerecord"
gem 'mysql2', '>= 0.3.18', '< 0.5'
gem 'activerecord-import'
gem "sugoi_bulk_insert"
