# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'minitest'
gem 'minitest-power_assert'
gem 'minitest-rg'
gem 'minitest-stub_any_instance'
gem 'pry'
gem 'pry-doc'
gem 'minispec-metadata'
