production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/production
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: 192.168.56.102
    port: 8983
    log_level: INFO

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/test

